name: Fuel Project CI/CD

# Trigger the workflow every time you push to the main branch
on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest

      - name: Run Tests
        run: |
          # This ensures your API and Model logic actually works before deploying
          pytest tests/ 

      - name: Build Docker Image
        run: |
          # Uses your existing API Dockerfile
          docker build -t fuel-consumption-api:latest -f Dockerfile.api .
